services:
  db:
    image: postgres:15
    container_name: my_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: vFtrDSpWLCunytYNUkQkiSWoXgZdaFzq
      POSTGRES_DB: railway

  app:
    build: .
    container_name: my_ai_bot
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - ./app:/app
    env_file:
      - app/.env

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data


volumes:
  redis_data: